
---
- name: 'apt update'
  become: true
  apt:
    update_cache: yes

- name: 'apt install npm and nodejs'
  become: true
  apt:
    name: ['npm', 'nodejs']
    state: latest
    update_cache: yes

- name: 'npm install pm2'
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present